import pygame as pg

AUTHOR = "kadraman's"
TITLE = "Galaxy Blast"
TXT_CREDITS = 'This game was written by kadraman'
GAME_OVER = "Game Over"
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60
ENEMY_MOVE_DOWN = 16
SPRITE_SHEET = './assets/images/spritesheet.png'
DEFAULT_FONT = './assets/fonts/BarcadeBrawlRegular.ttf'
DEFAULT_FONT_SIZE = 18
TITLE_FONT = "./assets/fonts/OASIS.TTF"
TITLE_FONT_SIZE = 48
GAME_OVER_FONT_SIZE = 32
DEFAULT_BACKGROUND = './assets/images/stars.png'
PLAY_SOUNDS = True
MAX_PLAYER_MISSILES = 2

# Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (0, 0, 0)
GREEN = (0, 0, 0)
BLUE = (0, 0, 0)

# user defined events
ADD_MINION_ENEMY = pg.USEREVENT + 1  # 25
ADD_MASTER_ENEMY = pg.USEREVENT + 2  # 26
ADD_BOSS_ENEMY = pg.USEREVENT + 3  # 27
DIVE_ENEMY = pg.USEREVENT + 4  # 27
LEAVE_ENEMY = pg.USEREVENT + 5  # 28
ENEMY_FIRES = pg.USEREVENT + 6  # 29

'''
all sprite width and height (once scaled)
'''
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
ENEMY1_WIDTH = 25
ENEMY1_HEIGHT = 25
ENEMY2_WIDTH = 25
ENEMY2_HEIGHT = 26
ENEMY3_WIDTH = 24
ENEMY3_HEIGHT = 20
MASTER_ENEMY_WIDTH = 30
MASTER_ENEMY_HEIGHT = 28
BOSS_ENEMY_WIDTH = 60
BOSS_ENEMY_HEIGHT = 60
MINE_WIDTH = 15
MINE_HEIGHT = 15
MISSILE_WIDTH = 5
MISSILE_HEIGHT = 16
EXPLOSION_WIDTH = 32
EXPLOSION_HEIGHT = 32
MISSILE_WIDTH = 5
MISSILE_HEIGHT = 16

'''
locations of sprites in sprite sheet
'''
# player ship
SS_PLAYER_IMAGES = 3
SS_PLAYER_WIDTH = 16
SS_PLAYER_HEIGHT = 20
SS_PLAYER_X_1 = 313
SS_PLAYER_Y_1 = 1
SS_PLAYER_X_2 = 331
SS_PLAYER_Y_2 = 1
SS_PLAYER_X_3 = 349
SS_PLAYER_Y_3 = 1
# minion enemies
SS_ENEMY1_IMAGES = 2
SS_ENEMY1_WIDTH = 10
SS_ENEMY1_HEIGHT = 10
SS_ENEMY1_X_1 = 45
SS_ENEMY1_Y_1 = 1
SS_ENEMY1_X_2 = 57
SS_ENEMY1_Y_2 = 1
#
SS_ENEMY2_IMAGES = 2
SS_ENEMY2_WIDTH = 11
SS_ENEMY2_HEIGHT = 10
SS_ENEMY2_X_1 = 69
SS_ENEMY2_Y_1 = 1
SS_ENEMY2_X_2 = 82
SS_ENEMY2_Y_2 = 1
#
SS_ENEMY3_IMAGES = 2
SS_ENEMY3_WIDTH = 13
SS_ENEMY3_HEIGHT = 8
SS_ENEMY3_X_1 = 95
SS_ENEMY3_Y_1 = 1
SS_ENEMY3_X_2 = 110
SS_ENEMY3_Y_2 = 1
# master enemy
SS_MASTER_ENEMY_IMAGES = 2
SS_MASTER_ENEMY_WIDTH = 15
SS_MASTER_ENEMY_HEIGHT = 14
SS_MASTER_ENEMY_X_1 = 227
SS_MASTER_ENEMY_Y_1 = 1
SS_MASTER_ENEMY_X_2 = 244
SS_MASTER_ENEMY_Y_2 = 1
# boss enemy
SS_BOSS_ENEMY_IMAGES = 2
SS_BOSS_ENEMY_WIDTH = 20
SS_BOSS_ENEMY_HEIGHT = 20
SS_BOSS_ENEMY_X_1 = 1
SS_BOSS_ENEMY_Y_1 = 1
SS_BOSS_ENEMY_X_2 = 23
SS_BOSS_ENEMY_Y_2 = 1
# mine
SS_MINE_IMAGES = 4
SS_MINE_WIDTH = 11
SS_MINE_HEIGHT = 11
SS_MINE_X = 261
SS_MINE_Y = 1
# missile
SS_MISSILE_IMAGES = 3
SS_MISSILE_WIDTH = 5
SS_MISSILE_HEIGHT = 16
SS_MISSILE_X_1 = 274
SS_MISSILE_Y_1 = 1
SS_MISSILE_X_2 = 281
SS_MISSILE_Y_2 = 1
SS_MISSILE_X_3 = 288
SS_MISSILE_Y_3 = 1
# explosion
SS_EXPLOSION_IMAGES = 3
SS_EXPLOSION_WIDTH = 32
SS_EXPLOSION_HEIGHT = 32
SS_EXPLOSION_X_1 = 125
SS_EXPLOSION_Y_1 = 1
SS_EXPLOSION_X_2 = 159
SS_EXPLOSION_Y_2 = 1
SS_EXPLOSION_X_3 = 193
SS_EXPLOSION_Y_3 = 1
# player lives
SS_PLAYER_LIVES_WIDTH = 16
SS_PLAYER_LIVES_HEIGHT = 16
SS_PLAYER_LIVES_X = 295
SS_PLAYER_LIVES_Y = 1

